apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-deployment
  labels:
    app: ai-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-api
  template:
    metadata:
      labels:
        app: ai-api
    spec:
      containers:
        - name: ai-api
          image: michielvdz/ai-api
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5000
          resources:
            limits:
              cpu: 1.0
              memory: "3Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: ai-api
  labels:
    app: ai-api
spec:
  type: NodePort
  selector:
    app: ai-api
  ports:
    - name: http
      port: 5000
      targetPort: 5000