name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7
      uses: docker/login-action@v1.12.0
      with:
        # Username used to log against the Docker registry
        username: michielvdz
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.7b3f717a-9915-4757-8b50-bdb1c49e9e58 }}
         
    - name: Build the Docker image
      run: docker build -t ai-api -f api/Dockerfile .
       
    - name: Tag the Docker image
      run: docker tag ai-api michielvdz/ai-api
       
    - name: Push the Docker image to dockerhub
      run: docker tag ai-api michielvdz/ai-api
